[package]
name = "internet-smol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-io = "1.13.0"
handlebars = "4.3.7"
rand = "0.8.5"
serde_json = "1.0.105"
smol = "1.3.0"
substring = "1.4.5"
